package org.ihtsdo.sct.drugmatch.match;

/**
 * @author dev-team@carecom.dk
 */
public enum MatchAttributeRule {

	AMBIGUOUS_MATCH,

	AMBIGUOUS_MATCH_EXCLUDING_DOSE_FORM_AND_UNIT,

	AMBIGUOUS_MATCH_EXCLUDING_UNIT,

	EXACT_MATCH,

	EXACT_MATCH_EXCLUDING_DOSE_FORM_AND_UNIT,

	EXACT_MATCH_EXCLUDING_UNIT,

	DOSE_FORM_MISSING_CHECK_CONCEPT,

	SUBSTANCE_MISSING_CHECK_CONCEPT,

	UNIT_MISSING_CHECK_CONCEPT,

	ZERO_MATCH;
}
